uv run cli.py \
    --path-to-pool-cache-train ./data/pool_cache_with_features_2026_02_01_train_debug.jsonl \
    --path-to-pool-cache-val ./data/pool_cache_with_features_2026_02_02_val_debug.jsonl \
	--path-to-baseline-model ./data/model_vk_video_266_1769078359_f.cb \
	--session-col-name userId \
	--alpha 0.5 \
    --formula-path fstorage:vk_video_266_1769078359_f \
    --loss-function PairLogitPairwise \
    --depth 3 \
    --timeout 600 \
    --n-trials 3 \
    --no-load-if-exists \
    --no-save-predictions \
	--no-calculate-regular-auc
